<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-HS68FTR" failures="2" tests="8" name="Retry Failed Test" time="0.189" errors="0" timestamp="2022-02-26T22:55:21 IST">
  <testcase classname="TestNGTutorials.RetryLogicTest" name="Test1" time="0.024">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="TestNGTutorials.RetryLogicTest" name="Test1" time="0.003">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="TestNGTutorials.RetryLogicTest" name="Test1" time="0.004">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="TestNGTutorials.RetryLogicTest" name="Test1" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at TestNGTutorials.RetryLogicTest.Test1(RetryLogicTest.java:12)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
  <testcase classname="TestNGTutorials.RetryLogicTest" name="Test2" time="0.003">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="TestNGTutorials.RetryLogicTest" name="Test2" time="0.003">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="TestNGTutorials.RetryLogicTest" name="Test2" time="0.003">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="TestNGTutorials.RetryLogicTest" name="Test2" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at TestNGTutorials.RetryLogicTest.Test2(RetryLogicTest.java:18)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
</testsuite> <!-- Retry Failed Test -->
